Keep r8 on Java 8 to prevent errors
Namely,

    Error: java.lang.IllegalArgumentException: Unsupported class file major version 61
    Compilation failed with an internal error.
    Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
            at com.android.tools.r8.utils.w.a(SourceFile:92)
            at com.android.tools.r8.R8.main(R8.java:4)
    Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
            at Version.fakeStackEntry(Version_3.0.73.java:0)
            at com.android.tools.r8.utils.w.a(SourceFile:68)
            at com.android.tools.r8.utils.w.a(SourceFile:28)
            at com.android.tools.r8.utils.w.a(SourceFile:27)
            at com.android.tools.r8.R8.b(R8.java:35)
            at com.android.tools.r8.R8.a(R8.java:1302)
            at com.android.tools.r8.utils.w.a(SourceFile:84)
            ... 1 more
    Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
            at com.android.tools.r8.internal.U6.<init>(SourceFile:10)
            at com.android.tools.r8.internal.U6.<init>(SourceFile:2)
            at com.android.tools.r8.internal.U6.<init>(SourceFile:1)
            at com.android.tools.r8.graph.B0.a(SourceFile:15)
            at com.android.tools.r8.utils.w.a(SourceFile:98)
            at com.android.tools.r8.utils.w.a(SourceFile:95)
            at com.android.tools.r8.graph.B0.b(SourceFile:2)
            at com.android.tools.r8.internal.P6.a(SourceFile:6)
            at com.android.tools.r8.internal.u6.a(SourceFile:8)
            at com.android.tools.r8.internal.u6.get(SourceFile:1)
            at com.android.tools.r8.internal.v6.b(SourceFile:28)
            at com.android.tools.r8.internal.v6.a(SourceFile:43)
            at com.android.tools.r8.graph.I0$b.<init>(SourceFile:7)
            at com.android.tools.r8.graph.I0.h(SourceFile:1)
            at com.android.tools.r8.graph.g0$b.<init>(SourceFile:8)
            at com.android.tools.r8.graph.I0.g(SourceFile:1)
            at com.android.tools.r8.R8.a(R8.java:46)
            at com.android.tools.r8.R8.c(R8.java:1)
            at com.android.tools.r8.R8.a(R8.java:1301)
            at com.android.tools.r8.utils.w.a(SourceFile:24)
            ... 4 more

will occur if r8 is run with Java 17.